### PR TITLE
Updated / improved German translation

### PR DESCRIPTION
**Pull request by valsu**
Corrections and stylistic improvements to the German translation

### CODE REVIEW

**Comment by foooomio** [comment]
Thanks!

Could you tell me the difference between "Hintergrundbild" and "Hintergrundgrafik"? Firefox uses "Hintergrundgrafik" as the name of the context menu item.

**Comment by valsu** [comment]
Sure :-)
"Hintergrundgrafik" means "background graphic". It's not wrong, but more general and technical. "Hintergrundbild" means "background image". It is both an exact translation from English and the term that is much more frequently used in German. Rarely any German would ever say "Hintergrundgrafik", professional graphic artists excluded maybe. I understand Firefox uses "Hintergrundgrafik", so it would make sense to keep that term. It just doesn't sound natural to me. Or maybe split the translation in two, one for Chromium/Chrome and one for Firefox?

**Comment by foooomio** [comment]
I understand. Thanks for your explanation! I'll merge and publish it.

**Comment by valsu** [comment]
My pleasure and thank you too for your work!

**Pull request merged**
